// Generated by gencpp from file romipi_fiducials/GetVisible.msg
// DO NOT EDIT!


#ifndef ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLE_H
#define ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLE_H

#include <ros/service_traits.h>


#include <romipi_fiducials/GetVisibleRequest.h>
#include <romipi_fiducials/GetVisibleResponse.h>


namespace romipi_fiducials
{

struct GetVisible
{

typedef GetVisibleRequest Request;
typedef GetVisibleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVisible
} // namespace romipi_fiducials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::romipi_fiducials::GetVisible > {
  static const char* value()
  {
    return "2f1d9a0bc9140638857d0d5a5f8f9d13";
  }

  static const char* value(const ::romipi_fiducials::GetVisible&) { return value(); }
};

template<>
struct DataType< ::romipi_fiducials::GetVisible > {
  static const char* value()
  {
    return "romipi_fiducials/GetVisible";
  }

  static const char* value(const ::romipi_fiducials::GetVisible&) { return value(); }
};


// service_traits::MD5Sum< ::romipi_fiducials::GetVisibleRequest> should match 
// service_traits::MD5Sum< ::romipi_fiducials::GetVisible > 
template<>
struct MD5Sum< ::romipi_fiducials::GetVisibleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::romipi_fiducials::GetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::GetVisibleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::romipi_fiducials::GetVisibleRequest> should match 
// service_traits::DataType< ::romipi_fiducials::GetVisible > 
template<>
struct DataType< ::romipi_fiducials::GetVisibleRequest>
{
  static const char* value()
  {
    return DataType< ::romipi_fiducials::GetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::GetVisibleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::romipi_fiducials::GetVisibleResponse> should match 
// service_traits::MD5Sum< ::romipi_fiducials::GetVisible > 
template<>
struct MD5Sum< ::romipi_fiducials::GetVisibleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::romipi_fiducials::GetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::GetVisibleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::romipi_fiducials::GetVisibleResponse> should match 
// service_traits::DataType< ::romipi_fiducials::GetVisible > 
template<>
struct DataType< ::romipi_fiducials::GetVisibleResponse>
{
  static const char* value()
  {
    return DataType< ::romipi_fiducials::GetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::GetVisibleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLE_H
