// Generated by gencpp from file romipi_fiducials/GetVisibleRequest.msg
// DO NOT EDIT!


#ifndef ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLEREQUEST_H
#define ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace romipi_fiducials
{
template <class ContainerAllocator>
struct GetVisibleRequest_
{
  typedef GetVisibleRequest_<ContainerAllocator> Type;

  GetVisibleRequest_()
    {
    }
  GetVisibleRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetVisibleRequest_

typedef ::romipi_fiducials::GetVisibleRequest_<std::allocator<void> > GetVisibleRequest;

typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleRequest > GetVisibleRequestPtr;
typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleRequest const> GetVisibleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace romipi_fiducials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'romipi_msgs': ['/home/jacob/catkin_ws/src/romipi_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romipi_fiducials/GetVisibleRequest";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetVisibleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::romipi_fiducials::GetVisibleRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLEREQUEST_H
