// Generated by gencpp from file romipi_fiducials/GetVisibleResponse.msg
// DO NOT EDIT!


#ifndef ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLERESPONSE_H
#define ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <romipi_msgs/NameList.h>

namespace romipi_fiducials
{
template <class ContainerAllocator>
struct GetVisibleResponse_
{
  typedef GetVisibleResponse_<ContainerAllocator> Type;

  GetVisibleResponse_()
    : visible_robots()  {
    }
  GetVisibleResponse_(const ContainerAllocator& _alloc)
    : visible_robots(_alloc)  {
  (void)_alloc;
    }



   typedef  ::romipi_msgs::NameList_<ContainerAllocator>  _visible_robots_type;
  _visible_robots_type visible_robots;





  typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetVisibleResponse_

typedef ::romipi_fiducials::GetVisibleResponse_<std::allocator<void> > GetVisibleResponse;

typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleResponse > GetVisibleResponsePtr;
typedef boost::shared_ptr< ::romipi_fiducials::GetVisibleResponse const> GetVisibleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace romipi_fiducials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'romipi_msgs': ['/home/jacob/catkin_ws/src/romipi_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f1d9a0bc9140638857d0d5a5f8f9d13";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f1d9a0bc9140638ULL;
  static const uint64_t static_value2 = 0x857d0d5a5f8f9d13ULL;
};

template<class ContainerAllocator>
struct DataType< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romipi_fiducials/GetVisibleResponse";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romipi_msgs/NameList visible_robots\n\
\n\
\n\
\n\
================================================================================\n\
MSG: romipi_msgs/NameList\n\
# list of robot name strings\n\
string[] names\n\
\n\
";
  }

  static const char* value(const ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.visible_robots);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetVisibleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::romipi_fiducials::GetVisibleResponse_<ContainerAllocator>& v)
  {
    s << indent << "visible_robots: ";
    s << std::endl;
    Printer< ::romipi_msgs::NameList_<ContainerAllocator> >::stream(s, indent + "  ", v.visible_robots);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMIPI_FIDUCIALS_MESSAGE_GETVISIBLERESPONSE_H
