// Generated by gencpp from file romipi_fiducials/ResetVisible.msg
// DO NOT EDIT!


#ifndef ROMIPI_FIDUCIALS_MESSAGE_RESETVISIBLE_H
#define ROMIPI_FIDUCIALS_MESSAGE_RESETVISIBLE_H

#include <ros/service_traits.h>


#include <romipi_fiducials/ResetVisibleRequest.h>
#include <romipi_fiducials/ResetVisibleResponse.h>


namespace romipi_fiducials
{

struct ResetVisible
{

typedef ResetVisibleRequest Request;
typedef ResetVisibleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetVisible
} // namespace romipi_fiducials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::romipi_fiducials::ResetVisible > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::romipi_fiducials::ResetVisible&) { return value(); }
};

template<>
struct DataType< ::romipi_fiducials::ResetVisible > {
  static const char* value()
  {
    return "romipi_fiducials/ResetVisible";
  }

  static const char* value(const ::romipi_fiducials::ResetVisible&) { return value(); }
};


// service_traits::MD5Sum< ::romipi_fiducials::ResetVisibleRequest> should match 
// service_traits::MD5Sum< ::romipi_fiducials::ResetVisible > 
template<>
struct MD5Sum< ::romipi_fiducials::ResetVisibleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::romipi_fiducials::ResetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::ResetVisibleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::romipi_fiducials::ResetVisibleRequest> should match 
// service_traits::DataType< ::romipi_fiducials::ResetVisible > 
template<>
struct DataType< ::romipi_fiducials::ResetVisibleRequest>
{
  static const char* value()
  {
    return DataType< ::romipi_fiducials::ResetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::ResetVisibleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::romipi_fiducials::ResetVisibleResponse> should match 
// service_traits::MD5Sum< ::romipi_fiducials::ResetVisible > 
template<>
struct MD5Sum< ::romipi_fiducials::ResetVisibleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::romipi_fiducials::ResetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::ResetVisibleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::romipi_fiducials::ResetVisibleResponse> should match 
// service_traits::DataType< ::romipi_fiducials::ResetVisible > 
template<>
struct DataType< ::romipi_fiducials::ResetVisibleResponse>
{
  static const char* value()
  {
    return DataType< ::romipi_fiducials::ResetVisible >::value();
  }
  static const char* value(const ::romipi_fiducials::ResetVisibleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROMIPI_FIDUCIALS_MESSAGE_RESETVISIBLE_H
