(cl:defpackage romipi_fiducials-srv
  (:use )
  (:export
   "GETPOSE"
   "<GETPOSE-REQUEST>"
   "GETPOSE-REQUEST"
   "<GETPOSE-RESPONSE>"
   "GETPOSE-RESPONSE"
   "GETVISIBLE"
   "<GETVISIBLE-REQUEST>"
   "GETVISIBLE-REQUEST"
   "<GETVISIBLE-RESPONSE>"
   "GETVISIBLE-RESPONSE"
   "RESETVISIBLE"
   "<RESETVISIBLE-REQUEST>"
   "RESETVISIBLE-REQUEST"
   "<RESETVISIBLE-RESPONSE>"
   "RESETVISIBLE-RESPONSE"
  ))

